#!/bin/bash

set -e

if [ -n $(grep "builds\.midonet\.org\/mem" /etc/yum.repos.d/*) ]; then
  echo "Installing MEM packages..."
  yum install -y midonet-manager midonet-tools midonet-elk midonet-jmxscraper lldpd midonet-cluster-mem
  yum install -y logstash elasticsearch
fi

exit 0
