#!/bin/bash

set -e

if [ -n "$(grep "repo\.midokura\.com\/mem" /etc/yum.repos.d/*)" ]; then
  echo "Installing MEM packages..."
  yum install -y midonet-manager midonet-tools midonet-jmxscraper lldpd midonet-cluster-mem
fi

if [ -n "$(grep "repo\.midokura\.com\/insights" /etc/yum.repos.d/*)" ]; then
  echo "Installing MEM packages..."
  yum install -y logstash elasticsearch
  yum install -y midonet-elk
fi

exit 0
